version: "2.1"

services:
    cms-db:
        image: mysql:5.6
        volumes:
            - "./shared/db:/var/lib/mysql"
        environment:
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        mem_limit: 1g
        env_file: config.env
        restart: always
        networks:
            - default
    cms-xmr:
        image: xibosignage/xibo-xmr:release-0.8
        ports:
            - "9505:9505"
        restart: always
        mem_limit: 256m
        env_file: config.env
        networks:
            - default
    cms-web:
        image: xibosignage/xibo-cms:release-2.3.2
        volumes:
            - "./shared/cms/custom:/var/www/cms/custom"
            - "./shared/backup:/var/www/backup"
            - "./shared/cms/web/theme/custom:/var/www/cms/web/theme/custom"
            - "./shared/cms/library:/var/www/cms/library"
            - "./shared/cms/web/userscripts:/var/www/cms/web/userscripts"
        restart: always
        links:
            - cms-db:mysql
            - cms-xmr:50001
        labels:
            - traefik.http.routers.cms-web.rule=Host(`signage.docker.sadatia.com`)
            - traefik.enable=true
            - traefik.docker.network=proxy_default
        environment:
            - XMR_HOST=cms-xmr
        env_file: config.env
        networks:
            - proxy_default
            - default
        ports:
            - "8082:80"
        mem_limit: 1g
    cms-quickchart:
      image: ianw/quickchart
            restart: always
      networks:
            - default
networks:
    proxy_default:
       external: true
    default:

